version: '3.8'

services:
  incognito-chat:
    build: .
    ports:
      - "3000:80"
    container_name: incognito-chat-app
    restart: unless-stopped

  # Development service (optional)
  incognito-chat-dev:
    build:
      context: .
      target: builder
    ports:
      - "5173:5173"
    container_name: incognito-chat-dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    profiles:
      - dev
